app:
  cors:
    allowed-origins: http://localhost:3000/, http://localhost:3006/
spring:
  datasource:
    url: jdbc:postgresql://localhost:6000/ewaiter
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
    initialization-mode: always
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
        ddl-auto: create

